argo-workflows:
  server:
    authModes:
      - server
  artifactRepositoryRef:
    # # -- 1st ConfigMap
    # # If you want to use this config map by default, name it "artifact-repositories".
    # # Otherwise, you can provide a reference to a
    # # different config map in `artifactRepositoryRef.configMap`.
    artifact-repositories:
      # -- v3.0 and after - if you want to use a specific key, put that key into this annotation.
      annotations:
        workflows.argoproj.io/default-artifact-repository: default-v1-s3-artifact-repository
      # 1st data of configmap. See above artifactRepository or customArtifactRepository.
      default-v1-s3-artifact-repository:
        archiveLogs: false
        s3:
          bucket: mybucket
          endpoint: my-release-minio:9000
          insecure: true
          accessKeySecret:
            name: minio-credentials
            key: accesskey
          secretKeySecret:
            name: minio-credentials
            key: secretkey

minio:
  persistence:
    ## @param persistence.enabled Enable MinIO&reg; data persistence using PVC. If false, use emptyDir
    ##
    enabled: false

kafka:
  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
      name: CLIENT
      sslClientAuth: ""
  controller:
    replicaCount: 3
